server {
    listen 8080;
    gzip on;
    gzip_types application/octet-stream;
    gzip_proxied no-cache no-store private expired auth;
    gzip_min_length 1000;
    client_max_body_size 150M;

    location / {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
        gzip_static on;
    }
}